version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chatbot-network

  # Optionally add a database service if needed
  # db:
  #   image: postgres:15-alpine
  #   container_name: chatbot-db
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=chatbot
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - chatbot-network

networks:
  chatbot-network:
    driver: bridge

# Uncomment if using database
# volumes:
#   postgres_data:
